import { Paper } from '../App';

export const mockPapers: Paper[] = [
  {
    id: '1',
    title: 'Attention Is All You Need: Transformer Architecture for Natural Language Processing',
    authors: ['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar', 'Jakob Uszkoreit'],
    abstract: 'We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train.',
    year: 2017,
    journal: 'Advances in Neural Information Processing Systems',
    citations: 47823,
    keywords: ['Transformer', 'Attention Mechanism', 'Neural Networks', 'Natural Language Processing'],
    category: 'Computer Science',
    doi: '10.5555/3295222.3295349',
    pdfUrl: 'https://example.com/paper1.pdf',
    isBookmarked: false,
    rating: 4.9
  },
  {
    id: '2',
    title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
    authors: ['Jacob Devlin', 'Ming-Wei Chang', 'Kenton Lee', 'Kristina Toutanova'],
    abstract: 'We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations by jointly conditioning on both left and right context.',
    year: 2018,
    journal: 'Conference of the North American Chapter of the Association for Computational Linguistics',
    citations: 34521,
    keywords: ['BERT', 'Language Model', 'Bidirectional', 'Pre-training'],
    category: 'Computer Science',
    doi: '10.18653/v1/N19-1423',
    pdfUrl: 'https://example.com/paper2.pdf',
    isBookmarked: false,
    rating: 4.8
  },
  {
    id: '3',
    title: 'Deep Residual Learning for Image Recognition',
    authors: ['Kaiming He', 'Xiangyu Zhang', 'Shaoqing Ren', 'Jian Sun'],
    abstract: 'Deeper neural networks are more difficult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs.',
    year: 2015,
    journal: 'IEEE Conference on Computer Vision and Pattern Recognition',
    citations: 89234,
    keywords: ['ResNet', 'Deep Learning', 'Computer Vision', 'Residual Learning'],
    category: 'Computer Science',
    doi: '10.1109/CVPR.2016.90',
    pdfUrl: 'https://example.com/paper3.pdf',
    isBookmarked: false,
    rating: 4.9
  },
  {
    id: '4',
    title: 'Generative Adversarial Networks',
    authors: ['Ian Goodfellow', 'Jean Pouget-Abadie', 'Mehdi Mirza', 'Bing Xu'],
    abstract: 'We propose a new framework for estimating generative models via an adversarial process, in which we simultaneously train two models: a generative model G that captures the data distribution, and a discriminative model D that estimates the probability that a sample came from the training data.',
    year: 2014,
    journal: 'Advances in Neural Information Processing Systems',
    citations: 45678,
    keywords: ['GAN', 'Generative Models', 'Adversarial Training', 'Deep Learning'],
    category: 'Computer Science',
    doi: '10.5555/2969033.2969125',
    pdfUrl: 'https://example.com/paper4.pdf',
    isBookmarked: false,
    rating: 4.7
  },
  {
    id: '5',
    title: 'Quantum Computing: An Applied Approach',
    authors: ['Hidary Stoffel', 'Sarah Chen', 'Michael Rodriguez'],
    abstract: 'This paper presents a comprehensive overview of quantum computing principles and their practical applications. We discuss quantum algorithms, error correction, and the current state of quantum hardware implementations.',
    year: 2023,
    journal: 'Nature Quantum Information',
    citations: 1234,
    keywords: ['Quantum Computing', 'Quantum Algorithms', 'Error Correction', 'Quantum Hardware'],
    category: 'Physics',
    doi: '10.1038/s41534-023-00001-1',
    pdfUrl: 'https://example.com/paper5.pdf',
    isBookmarked: false,
    rating: 4.6
  },
  {
    id: '6',
    title: 'CRISPR-Cas9 Gene Editing: Applications and Ethical Considerations',
    authors: ['Jennifer Doudna', 'Emmanuelle Charpentier', 'Feng Zhang'],
    abstract: 'The CRISPR-Cas9 system has revolutionized gene editing by providing a precise, efficient, and cost-effective method for modifying DNA sequences. This review discusses recent advances in CRISPR technology and addresses the ethical implications of human genome editing.',
    year: 2022,
    journal: 'Cell',
    citations: 8765,
    keywords: ['CRISPR', 'Gene Editing', 'Genome Modification', 'Bioethics'],
    category: 'Biology',
    doi: '10.1016/j.cell.2022.01.001',
    pdfUrl: 'https://example.com/paper6.pdf',
    isBookmarked: false,
    rating: 4.8
  },
  {
    id: '7',
    title: 'Climate Change Impacts on Global Food Security',
    authors: ['Maria Santos', 'James Williams', 'Li Wei', 'Ahmed Hassan'],
    abstract: 'This study examines the relationship between climate change and global food security, analyzing temperature and precipitation patterns and their effects on crop yields across different regions. We present projections for future food production under various climate scenarios.',
    year: 2023,
    journal: 'Nature Climate Change',
    citations: 892,
    keywords: ['Climate Change', 'Food Security', 'Agriculture', 'Crop Yields'],
    category: 'Biology',
    doi: '10.1038/s41558-023-01234-x',
    pdfUrl: 'https://example.com/paper7.pdf',
    isBookmarked: false,
    rating: 4.5
  },
  {
    id: '8',
    title: 'Renewable Energy Storage: Advances in Battery Technology',
    authors: ['Elena Petrov', 'David Kim', 'Carlos Rodriguez'],
    abstract: 'This paper reviews recent advances in battery technology for renewable energy storage, including lithium-ion, solid-state, and emerging battery chemistries. We discuss the challenges and opportunities in scaling up energy storage solutions.',
    year: 2023,
    journal: 'Nature Energy',
    citations: 567,
    keywords: ['Battery Technology', 'Energy Storage', 'Renewable Energy', 'Lithium-ion'],
    category: 'Chemistry',
    doi: '10.1038/s41560-023-01234-5',
    pdfUrl: 'https://example.com/paper8.pdf',
    isBookmarked: false,
    rating: 4.4
  }
];